### ISSUE TITLE
Support for newer `xarray` versions?

### ISSUE THREAD

**Issue by m-albert** [bioio-devs/bioio-czi#14]
Hi, we recently migrated from `aicsimageio` to `bioio` at https://github.com/multiview-stitcher/multiview-stitcher and realised `bioio-czi` has a requirement for

https://github.com/bioio-devs/bioio-czi/blob/5a26a300a128a2ac0e3b7d605432789ca427f553/pyproject.toml#L37

Could this be updated to a newer version of `xarray`?

Thanks a lot in advance and I'm happy to help with any testing.

**Comment by evamaxfield** [comment]
First, thanks for migrating! ❤️

Second, #15 will resolve this at least for xarray and dask upper bounds, checking numpy now!

I'll release a new version after it's merged if I have @toloudis @BrianWhitneyAI approval.

**Comment by toloudis** [comment]
@evamaxfield would you mind bumping aicspylibczi dep to >=3.2.0  also?

**Comment by evamaxfield** [comment]
Release is now available: https://pypi.org/project/bioio-czi/ 🙂
